# Generated by Django 4.0.6 on 2022-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=10, max_digits=20)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita')], default='D', max_length=1)),
            ],
        ),
    ]
