# Generated by Django 4.0.6 on 2022-09-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento_familiar', '0002_despesa_receita_delete_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='tipo',
        ),
    ]
